#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
BG_UNGU="\033[45;1m"
pink="\033[1;35m"
BLUE="\033[4;34m"
BG_BLU="\033[44;1m" # BG BIRU
Xark='\e[0m'
GREN="\033[92m"
clear

function baris_panjang() {
  echo -e "${pink}────────────────────────────────────────${Xark}"
}
function ATAS() {
  echo -e     "${BG_UNGU}\e[97m         SSH-Dropbear-OpenVPN           ${Xark} "
}

# . Create Ssh
function Create_Ssh() {
  add-ssh
}

# . Create Triall
function Create_Trial() {
  trial-ssh
}

# . Hapus akun ssh
function Delete_Ssh(){
  del-ssh
}

# . List Member ssh
function List_Member() {
  member-ssh
}

# . Auto Kill ssh
function Auto_Kill() {
  auto-kill
}

# . Check user Login
function Check_Mullog() {
  limitssh-ip
}

# . Delete Expiry
function Delete_Exp() {
  delexp
}

# . Changes Limit
function Changes_Limit() {
  limit-on-off
}

# . Limit On off
function Limit_On_Off() {
  Lt-on-off
}

#. Renew Ssh
function Renew_Ssh() {
  renew-ssh
}

# . Lock Ssh
function Lock() {
  lock
}

# . Unlock Ssh
function Unlock() {
  unlock
}

# . Detail Akun Ssh
function Details_Account(){
  user-ssh
}

function Monitor_Ssh() {
  ceklim
}

function Recovery_Ssh() {
  recover
}

# . Banner Ssh
function Banner() {
  baris_panjang
  ATAS
  baris_panjang
}
function Menu_Features() {
  echo -e "  1.)  Create Accounts"
  echo -e "  2.)  Delete Accounts"
  echo -e "  3.)  Renew Accounts"
  echo -e "  4.)  Trial Accounts"
  echo -e "  5.)  List Member Accounts"
  echo -e "  6.)  List Expired Accounts"
  echo -e "  7.)  Lock Accounts"
  echo -e "  8.)  Unlock Accounts"
  echo -e "  9.)  Edit Limit IP Account"
  echo -e " 10.)  Limit IP On Off Accounts"
  echo -e " 11.)  Auto Kill Accounts "
  echo -e " 12.)  Detail Accounts"
  echo -e " 13.)  Check Users Login"
  echo -e " 14.)  Check Login UDP"
  echo -e " 15.)  Back to Menu"
  echo -e "  x.)  Exit"
  baris_panjang
}

Banner
Menu_Features
read -p "Select From Options [1-15 or x] :  " prass
case $prass in
1) clear ; Create_Ssh ;;
2) clear ; Delete_Ssh ;;
3) clear ; renew-ssh ;;
4) clear ; Create_Trial ;;
5) clear ; List_Member ;;
6) clear ; Delete_Exp ;;
7) clear ; Lock ;;
8) clear ; Unlock ;;
9) clear ; ganti-ip-ssh ;;
10) clear ; Limit_On_Off ;;
11) clear ; Check_Mullog ;;
12) clear ; Details_Account ;;
13) clear ; Monitor_Ssh ;;
14) clear ; cekudp ;;
15) clear ; menu ;;
x) exit ;;
*) m-ssh ;;
esac
