#!/bin/bash
REDBLD="\033[0m\033[91;1m"
Green="\e[92;1m"
RED="\033[1;31m"
YELLOW="\033[33m"
PURPLE='\033[0;35m'
White="\033[97;1m"
BG_BLU="\033[44;1m" # BG BIRU
BG_UNGU="\033[45;1m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
NC='\e[0m'
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
#IPVPS=$(curl -s ipv4.icanhazip.com)
#ISP=$(cat /etc/xray/isp)
#CITY=$(cat /etc/xray/city)
#domain=$(cat /etc/xray/domain)
#RAM=$(free -m | awk 'NR==2 {print $2}')
#MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')

#uptime="$(uptime -p | cut -d " " -f 2-10)"
#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
#cpu_usage+=" %"
# // Gettings Info
function print_install() {
echo -e "${BLUE} =============================== ${FONT}"
echo -e "${YELLOW} # $1 ${FONT}"
echo -e "${BLUE} =============================== ${FONT}"
sleep 1
}
function print_success() {
if [[ 0 -eq $? ]]; then
echo -e "${BLUE} =============================== ${FONT}"
echo -e "${Green} # $1 berhasil dipasang"
echo -e "${BLUE} =============================== ${FONT}"
sleep 2
fi
}

######################################
# // USERNAME IZIN IPP
rm -f /usr/bin/user
username=$(curl -sS https://raw.githubusercontent.com/MasPras0/ip/refs/heads/main/ip | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS https://raw.githubusercontent.com/MasPras0/ip/refs/heads/main/ip | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
if [[ $certifacate -le 0 ]]; then
masaaktif="EXPAIRED"
else
masaaktif="${certifacate} Day"
fi
clear
######################################
# // GETTINGS SYSTEM
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="\033[1;92mON${NC}"
else
   status_ssh="\033[91;1mOFF${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="\033[1;92mON${NC}"
else
    status_ws_epro="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="\033[1;92mON${NC}"
else
   status_haproxy="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="\033[1;92mON${NC}"
else
   status_xray="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="\033[1;92mON${NC}"
else
   status_nginx="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING DROPBEAR
######################################
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="\033[1;92mGOOD${NC}"
else
   status_dropbear="\033[91;1mCRAZY${NC} "
fi

# \\ Vless account //
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
# \\ Vmess account //
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
# \\ Trojan account //
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
# \\ shadowsocks account //
ssx=$(grep -c -E "^#!# " "/etc/xray/config.json")
let ssa=$ssx/2

kemarin=$(date -d "-1 days" +"%m-%d")
hariini=$(date -d "0 days" +"%m-%d")
kemarin1=$(date -d "-1 days" +"%m/%d")
hariini1=$(date -d "0 days" +"%m/%d")
bulan=$(date +"%b '%y")
bulan1=$(date +"%Y-%m")
kemarin2=$(vnstat -d | grep -w "${kemarin}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
kemarin3=$(vnstat -d | grep -w "${kemarin1}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
if [[ $kemarin2 == "" ]]; then
bwkmrn=${kemarin3}
else
bwkmrn=${kemarin2}
fi
if [[ $bwkmrn == "" ]]; then
bwkmrn1=${kemarin1}
else
bwkmrn1=${bwkmrn}
fi
hariini2=$(vnstat -d | grep -w "${hariini}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
hariini3=$(vnstat -d | grep -w "${hariini1}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
if [[ $hariini2 == "" ]]; then
bwhari=${hariini3}
else
bwhari=${hariini2}
fi
bulan2=$(vnstat -m | grep -w "${bulan}" | awk '{print $9" "substr ($10 ,1 ,1) substr ($10 ,3 ,1)}') 
bulan3=$(vnstat -m | grep -w "${bulan1}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
if [[ $bulan2 == "" ]]; then
bwbln=${bulan3}
else
bwbln=${bulan2}
fi

function Newbie_Banner() {
clear
echo -e "\033[1;35m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[1;35m│${BG_UNGU} \e[97m               PRASS TUNNELING                  \e[0m\e[1;35m│\033[96;1m"
echo -e "\033[1;35m└─────────────────────═━☾☽━═──────────────────────┘\033[0m "
}



function Service_System_Operating() {
echo -e "\033[1;35m ───────────────────────────────────────────────── \033[0m "
echo -e "\033[96;1m \e[97m SYSTEM       : $(cat /etc/os-release | grep -w PRETTY_NAME | head -n1| sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')     \033[0m "
echo -e "\033[96;1m \e[97m RAM          : $(free -m | awk 'NR==2 {print $2}')    \033[0m "
echo -e "\033[96;1m \e[97m UPTIME       : $(uptime -p | cut -d " " -f 2-10)\033[0m "
echo -e "\033[96;1m \e[97m IP VPS       : $(curl -s ipv4.icanhazip.com)     \033[0m "
echo -e "\033[96;1m \e[97m CITY         : $(cat /etc/xray/city)    \033[0m "
echo -e "\033[96;1m \e[97m ISP          : $(cat /etc/xray/isp)    \033[0m "
echo -e "\033[96;1m \e[97m DOMAIN       : $(cat /etc/xray/domain)    \033[0m "
echo -e "\033[96;1m \e[97m VERSION      : $(cat /opt/.ver)    \033[0m " 
echo -e "\033[96;1m \e[97m CLIENTS      :\033[0m\033[91;1m $(cat /usr/bin/user)      \033[0m "
echo -e "\033[96;1m \e[97m Expiry       :\033[0m\033[91;1m $masaaktif  \033[0m "
echo -e "\033[1;35m ───────────────────────────────────────────────── \033[0m "
}



function Service_Status() {
echo -e "\033[96;1m  \e[0m\e[33m PROXY :\e[0m $status_haproxy  \e[0m|\e[33m NGINX :\e[0m $status_nginx  \e[0m|\e[33m XRAY :\e[0m $status_xray \e[0m| $status_dropbear  \e[96;1m   \e[0m "
echo -e "\033[1;35m ───────────────────────────────────────────────── \033[0m "
}

function List_All_Account() {
echo -e "\033[1;35m         ┌──────────────────────────────┐\033[0m "
echo -e "\033[97;1m              SSH OPENVPN  :   $ssh1         \033[0m " 
echo -e "\033[97;1m              VLESS XRAY   :   $vla          \033[0m " 
echo -e "\033[97;1m              VMESS XRAY   :   $vma          \033[0m " 
echo -e "\033[97;1m              TRJAN XRAY   :   $trb          \033[0m " 
echo -e "\033[97;1m              SSR-LIBEV    :   $ssa          \033[0m "   
echo -e "\033[1;35m         └──────────────────────────────┘\033[0m "
}


function Details_Bw_Clients() {
echo -e "\033[1;35m ───────────────────────────────────────────────── \033[0m "
echo -e "\033[96;1m  \e[0m\e[33m HARI INI :\e[0m ${bwhari}  \e[0m|  \e[33m KEMARIN : \e[0m ${bwkmrn1}  \e[0m\033[0m "
}

function Acces_Use_Command() {
echo -e "\033[1;35m ───────────────────────────────────────────────── \033[0m "
echo -e "\033[96;1m       \e[33m1.)\e[97m SSH/OPENVPN   \e[33m5.)\e[97m BOT TELEGRAM   \e[96;1m\e[0m"   
echo -e "\033[96;1m       \e[33m2.)\e[97m XRAY MANAGER  \e[33m6.)\e[97m BACKUP RESTOR  \e[96;1m\e[0m"
echo -e "\033[96;1m       \e[33m3.)\e[97m XRAY TROJAN   \e[33m7.)\e[97m FEATURES       \e[96;1m\e[0m"
echo -e "\033[96;1m       \e[33m4.)\e[97m SLOWDNS       \e[33m8.)\e[97m REBOOT         \e[96;1m\e[0m"
echo -e "\033[1;35m ───────────────────────═━☾☽━═────────────────────\033[0m "
}

function Select_Display() {
echo
read -p "Select From option [1/8 or x] :  " hallo
case $hallo in
1) clear ; m-ssh ;; # menu ssh
2) clear ; m-xray ;; # menu vmess
3) clear ; m-tro ;; # menu trojan
4) clear ; sd ;; # menu slowdns
5) clear ; m-bot ;; # menu bot telegram
6) clear ; m-bkp ;; # menu backup
7) clear ; m-ftr ;; # menu features
8) clear ; reboot ;; # reboot system
*) welcome ;; # Back To Home Welcome
esac
}

clear && printf '\033[3J'
Newbie_Banner
Service_System_Operating
Service_Status
List_All_Account
Details_Bw_Clients
Acces_Use_Command
Select_Display
