#!/bin/bash

SCRIPT_PATH="/usr/bin/m"
SERVICE_PATH="/etc/systemd/system/m.service"

cat << 'EOF' > "$SCRIPT_PATH"
#!/bin/bash

SERVICES=("xray" "nginx" "ws" "haproxy")

while true; do
    for service in "${SERVICES[@]}"; do
        if ! systemctl is-active --quiet "$service"; then
            echo "$(date) - $service mati! Merestart..." >> /var/log/service_monitor.log
            systemctl restart "$service"
        fi
    done
    sleep 5
done
EOF

chmod +x "$SCRIPT_PATH"

cat << EOF > "$SERVICE_PATH"
[Unit]
Description=Service Monitor (Auto Restart)
After=network.target

[Service]
ExecStart=$SCRIPT_PATH
Restart=always
User=root

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable m
systemctl start m

